### ISSUE TITLE
Docusign connect show invalid integrator key

### ISSUE THREAD

**Issue by kma77** [Acumatica/Acumatica-eSign#2]
When connect use Docsgin, it gives error 'invetrator key is invalid' but i dont see any place can enter a integrator key

**Comment by DhirenChhapgar** [comment]
You are not required to obtain DocuSign Integrator key if you are using eSign integration AddOn package provided by Acumatica (Available at https://portal.acumatica.com/downloads/marketplace-solutions/). 

However, if you are creating package by own locally reffering this code with or without any modification then you're required to obtain integration key by your own from DocuSign.

**Comment by kma77** [comment]
Hi Dhiren

I am integrating Acumatica-esign into our ERP solution, however it gives invalied integrator key error when i tried to connect, and i also found the key was hard coded in the project.

Can we have a session to talk about this, your help is very much appreciated

Regards
Kevin
________________________________
